export enum GameUpdateType {
    CONNECTION_STATUS_UPDATE = "CONNECTION_STATUS_UPDATE",
    GAME_STATE_SNAPSHOT_UPDATE = "GAME_STATE_SNAPSHOT_UPDATE",
    PLAYER_ACTION_UPDATE = "PLAYER_ACTION_UPDATE",
    PLAYER_HAND_UPDATE = "PLAYER_HAND_UPDATE",
    PLAYER_SETUP_UPDATE = "PLAYER_SETUP_UPDATE",
    PLAYER_TURN_UPDATE = "PLAYER_TURN_UPDATE",
    ROUND_STATE_UPDATE = "ROUND_STATE_UPDATE",
    SERVER_MESSAGE_UPDATE = "SERVER_MESSAGE_UPDATE",
    SHOWDOWN_RESULT_UPDATE = "SHOWDOWN_RESULT_UPDATE"
}
